export const mockSchools = [
  {
    id: "1",
    name: "University of Lagos",
    shortName: "UNILAG",
    country: "Nigeria",
    city: "Lagos",
    address: "University Road, Akoka, Lagos",
    email: "admin@unilag.edu.ng",
    phone: "+234 1 820 1000",
    plan: "Enterprise",
    status: "active" as const,
    totalStudents: 12458,
    totalProfessors: 342,
    totalCourses: 856,
    avgAttendance: 87.5,
    onboardedAt: "2024-01-15",
    logo: null,
  },
  {
    id: "2",
    name: "Obafemi Awolowo University",
    shortName: "OAU",
    country: "Nigeria",
    city: "Ile-Ife",
    address: "Obafemi Awolowo University, Ile-Ife, Osun State",
    email: "admin@oauife.edu.ng",
    phone: "+234 36 232 615",
    plan: "Professional",
    status: "active" as const,
    totalStudents: 8932,
    totalProfessors: 210,
    totalCourses: 512,
    avgAttendance: 83.2,
    onboardedAt: "2024-02-20",
    logo: null,
  },
  {
    id: "3",
    name: "Ahmadu Bello University",
    shortName: "ABU",
    country: "Nigeria",
    city: "Zaria",
    address: "Samaru, Zaria, Kaduna State",
    email: "admin@abu.edu.ng",
    phone: "+234 69 550 700",
    plan: "Professional",
    status: "active" as const,
    totalStudents: 10201,
    totalProfessors: 289,
    totalCourses: 634,
    avgAttendance: 79.8,
    onboardedAt: "2024-03-10",
    logo: null,
  },
  {
    id: "4",
    name: "University of Ibadan",
    shortName: "UI",
    country: "Nigeria",
    city: "Ibadan",
    address: "University of Ibadan, Ibadan, Oyo State",
    email: "admin@ui.edu.ng",
    phone: "+234 2 810 1000",
    plan: "Starter",
    status: "trial" as const,
    totalStudents: 5400,
    totalProfessors: 140,
    totalCourses: 310,
    avgAttendance: 91.1,
    onboardedAt: "2024-05-01",
    logo: null,
  },
  {
    id: "5",
    name: "Covenant University",
    shortName: "CU",
    country: "Nigeria",
    city: "Ota",
    address: "Km 10 Idiroko Road, Canaan Land, Ota, Ogun State",
    email: "admin@covenantuniversity.edu.ng",
    phone: "+234 1 790 4900",
    plan: "Enterprise",
    status: "active" as const,
    totalStudents: 7800,
    totalProfessors: 190,
    totalCourses: 420,
    avgAttendance: 94.3,
    onboardedAt: "2024-01-30",
    logo: null,
  },
  {
    id: "6",
    name: "Federal University of Technology",
    shortName: "FUTA",
    country: "Nigeria",
    city: "Akure",
    address: "PMB 704, Akure, Ondo State",
    email: "admin@futa.edu.ng",
    phone: "+234 34 230 500",
    plan: "Starter",
    status: "inactive" as const,
    totalStudents: 3200,
    totalProfessors: 89,
    totalCourses: 198,
    avgAttendance: 0,
    onboardedAt: "2024-04-12",
    logo: null,
  },
];

export const attendanceTrend = [
  { month: "Jan", attendance: 82, target: 85 },
  { month: "Feb", attendance: 84, target: 85 },
  { month: "Mar", attendance: 86, target: 85 },
  { month: "Apr", attendance: 83, target: 85 },
  { month: "May", attendance: 88, target: 85 },
  { month: "Jun", attendance: 87, target: 85 },
];

export const schoolsByPlan = [
  { plan: "Enterprise", count: 2, color: "#4f46e5" },
  { plan: "Professional", count: 2, color: "#7c3aed" },
  { plan: "Starter", count: 2, color: "#a78bfa" },
];

export const recentActivity = [
  { id: 1, action: "New school onboarded", subject: "Federal University of Technology", time: "2 hours ago", type: "onboard" },
  { id: 2, action: "Plan upgraded", subject: "Covenant University → Enterprise", time: "5 hours ago", type: "upgrade" },
  { id: 3, action: "Support ticket raised", subject: "Ahmadu Bello University", time: "1 day ago", type: "ticket" },
  { id: 4, action: "New school onboarded", subject: "University of Ibadan", time: "2 days ago", type: "onboard" },
  { id: 5, action: "School suspended", subject: "Federal University of Technology", time: "3 days ago", type: "suspend" },
];

export const mockFaculties = [
  { id: "1", name: "Engineering", dean: "Prof. John Adeyemi", color: "#3b82f6", departments: 8, professors: 145, students: 3250 },
  { id: "2", name: "Business & Economics", dean: "Dr. Maria Okafor", color: "#7c3aed", departments: 5, professors: 89, students: 2180 },
  { id: "3", name: "Medical Sciences", dean: "Dr. James Eze", color: "#ef4444", departments: 6, professors: 98, students: 1890 },
  { id: "4", name: "Arts & Humanities", dean: "Prof. Sarah Bello", color: "#f97316", departments: 7, professors: 76, students: 1540 },
];

export const mockDepartments = [
  { id: "1", name: "Computer Science", faculty: "Engineering", hod: "Dr. Chukwu", professors: 24, students: 560, courses: 48, attendanceRate: 88.5 },
  { id: "2", name: "Electrical Engineering", faculty: "Engineering", hod: "Prof. Alade", professors: 18, students: 412, courses: 36, attendanceRate: 82.1 },
  { id: "3", name: "Mechanical Engineering", faculty: "Engineering", hod: "Dr. Ibrahim", professors: 20, students: 490, courses: 40, attendanceRate: 79.3 },
  { id: "4", name: "Business Administration", faculty: "Business & Economics", hod: "Dr. Osei", professors: 16, students: 680, courses: 32, attendanceRate: 91.0 },
  { id: "5", name: "Economics", faculty: "Business & Economics", hod: "Prof. Nwachukwu", professors: 14, students: 520, courses: 28, attendanceRate: 85.7 },
  { id: "6", name: "Medicine", faculty: "Medical Sciences", hod: "Dr. Adeyemi", professors: 30, students: 340, courses: 60, attendanceRate: 95.2 },
];

export const mockProfessors = [
  { id: "p1", name: "Prof. John Adeyemi", email: "j.adeyemi@unilag.edu.ng", department: "Computer Science", school: "UNILAG", courses: 4, students: 320, joinedAt: "2022-08-01", status: "active" as const },
  { id: "p2", name: "Dr. Amaka Okonkwo", email: "a.okonkwo@unilag.edu.ng", department: "Electrical Engineering", school: "UNILAG", courses: 3, students: 210, joinedAt: "2021-09-01", status: "active" as const },
  { id: "p3", name: "Prof. Emeka Nwachukwu", email: "e.nwachukwu@unilag.edu.ng", department: "Mechanical Engineering", school: "UNILAG", courses: 5, students: 280, joinedAt: "2020-01-15", status: "active" as const },
  { id: "p4", name: "Dr. Fatima Aliyu", email: "f.aliyu@oau.edu.ng", department: "Business Administration", school: "OAU", courses: 3, students: 390, joinedAt: "2023-02-01", status: "active" as const },
  { id: "p5", name: "Prof. Tunde Olatunji", email: "t.olatunji@oau.edu.ng", department: "Economics", school: "OAU", courses: 4, students: 245, joinedAt: "2019-08-01", status: "active" as const },
  { id: "p6", name: "Dr. Chioma Eze", email: "c.eze@abu.edu.ng", department: "Medicine", school: "ABU", courses: 6, students: 180, joinedAt: "2021-03-01", status: "active" as const },
  { id: "p7", name: "Prof. Akin Babatunde", email: "a.babatunde@abu.edu.ng", department: "Computer Science", school: "ABU", courses: 4, students: 310, joinedAt: "2022-07-01", status: "inactive" as const },
  { id: "p8", name: "Dr. Grace Okoro", email: "g.okoro@ui.edu.ng", department: "Arts & Humanities", school: "UI", courses: 3, students: 165, joinedAt: "2023-09-01", status: "active" as const },
];

export const mockStudents = [
  { id: "s1", name: "Adebayo Ogundimu", matricNo: "190501001", email: "a.ogundimu@student.unilag.edu.ng", department: "Computer Science", school: "UNILAG", level: "400", attendanceRate: 92.3, status: "active" as const, enrolledAt: "2019-08-01" },
  { id: "s2", name: "Chidinma Okafor", matricNo: "200501045", email: "c.okafor@student.unilag.edu.ng", department: "Electrical Engineering", school: "UNILAG", level: "300", attendanceRate: 78.5, status: "active" as const, enrolledAt: "2020-08-01" },
  { id: "s3", name: "Mohammed Bello", matricNo: "210501023", email: "m.bello@student.unilag.edu.ng", department: "Mechanical Engineering", school: "UNILAG", level: "200", attendanceRate: 65.2, status: "active" as const, enrolledAt: "2021-08-01" },
  { id: "s4", name: "Oluwaseun Adeyemi", matricNo: "220101067", email: "o.adeyemi@student.oau.edu.ng", department: "Business Administration", school: "OAU", level: "100", attendanceRate: 88.9, status: "active" as const, enrolledAt: "2022-08-01" },
  { id: "s5", name: "Ngozi Eze", matricNo: "190201031", email: "n.eze@student.oau.edu.ng", department: "Economics", school: "OAU", level: "400", attendanceRate: 95.1, status: "active" as const, enrolledAt: "2019-08-01" },
  { id: "s6", name: "Emeka Obi", matricNo: "210301012", email: "e.obi@student.abu.edu.ng", department: "Medicine", school: "ABU", level: "300", attendanceRate: 97.8, status: "active" as const, enrolledAt: "2021-09-01" },
  { id: "s7", name: "Aisha Mohammed", matricNo: "220401088", email: "a.mohammed@student.abu.edu.ng", department: "Computer Science", school: "ABU", level: "200", attendanceRate: 72.4, status: "active" as const, enrolledAt: "2022-09-01" },
  { id: "s8", name: "Taiwo Akinwale", matricNo: "200101055", email: "t.akinwale@student.ui.edu.ng", department: "Arts & Humanities", school: "UI", level: "300", attendanceRate: 58.3, status: "suspended" as const, enrolledAt: "2020-08-01" },
  { id: "s9", name: "Kemi Fashola", matricNo: "230501099", email: "k.fashola@student.unilag.edu.ng", department: "Computer Science", school: "UNILAG", level: "100", attendanceRate: 91.0, status: "active" as const, enrolledAt: "2023-08-01" },
  { id: "s10", name: "Uche Okafor", matricNo: "210501099", email: "u.okafor@student.unilag.edu.ng", department: "Electrical Engineering", school: "UNILAG", level: "200", attendanceRate: 83.6, status: "active" as const, enrolledAt: "2021-08-01" },
];

export const mockCourses = [
  { id: "c1", code: "CSC401", title: "Advanced Database Systems", department: "Computer Science", school: "UNILAG", professor: "Prof. John Adeyemi", students: 87, semester: "First", level: "400", attendanceRate: 89.2, status: "active" as const },
  { id: "c2", code: "CSC301", title: "Operating Systems", department: "Computer Science", school: "UNILAG", professor: "Prof. John Adeyemi", students: 124, semester: "First", level: "300", attendanceRate: 82.7, status: "active" as const },
  { id: "c3", code: "EEE401", title: "Control Systems Engineering", department: "Electrical Engineering", school: "UNILAG", professor: "Dr. Amaka Okonkwo", students: 68, semester: "First", level: "400", attendanceRate: 91.5, status: "active" as const },
  { id: "c4", code: "MEE301", title: "Thermodynamics II", department: "Mechanical Engineering", school: "UNILAG", professor: "Prof. Emeka Nwachukwu", students: 95, semester: "Second", level: "300", attendanceRate: 76.3, status: "active" as const },
  { id: "c5", code: "BUS401", title: "Strategic Management", department: "Business Administration", school: "OAU", professor: "Dr. Fatima Aliyu", students: 142, semester: "First", level: "400", attendanceRate: 93.8, status: "active" as const },
  { id: "c6", code: "ECO301", title: "Macroeconomics III", department: "Economics", school: "OAU", professor: "Prof. Tunde Olatunji", students: 108, semester: "First", level: "300", attendanceRate: 87.4, status: "active" as const },
  { id: "c7", code: "MED301", title: "Pharmacology II", department: "Medicine", school: "ABU", professor: "Dr. Chioma Eze", students: 62, semester: "First", level: "300", attendanceRate: 98.1, status: "active" as const },
  { id: "c8", code: "CSC201", title: "Data Structures & Algorithms", department: "Computer Science", school: "ABU", professor: "Prof. Akin Babatunde", students: 110, semester: "Second", level: "200", attendanceRate: 79.6, status: "inactive" as const },
];

export const mockAttendanceRecords = [
  { id: "a1", date: "2025-05-20", course: "CSC401 – Advanced Database Systems", school: "UNILAG", professor: "Prof. John Adeyemi", enrolled: 87, present: 78, percentage: 89.7, sessionType: "Lecture", verified: true },
  { id: "a2", date: "2025-05-20", course: "EEE401 – Control Systems Engineering", school: "UNILAG", professor: "Dr. Amaka Okonkwo", enrolled: 68, present: 64, percentage: 94.1, sessionType: "Lecture", verified: true },
  { id: "a3", date: "2025-05-19", course: "CSC301 – Operating Systems", school: "UNILAG", professor: "Prof. John Adeyemi", enrolled: 124, present: 99, percentage: 79.8, sessionType: "Lab", verified: true },
  { id: "a4", date: "2025-05-19", course: "BUS401 – Strategic Management", school: "OAU", professor: "Dr. Fatima Aliyu", enrolled: 142, present: 138, percentage: 97.2, sessionType: "Lecture", verified: true },
  { id: "a5", date: "2025-05-18", course: "MEE301 – Thermodynamics II", school: "UNILAG", professor: "Prof. Emeka Nwachukwu", enrolled: 95, present: 71, percentage: 74.7, sessionType: "Lecture", verified: false },
  { id: "a6", date: "2025-05-18", course: "MED301 – Pharmacology II", school: "ABU", professor: "Dr. Chioma Eze", enrolled: 62, present: 61, percentage: 98.4, sessionType: "Clinic", verified: true },
  { id: "a7", date: "2025-05-17", course: "ECO301 – Macroeconomics III", school: "OAU", professor: "Prof. Tunde Olatunji", enrolled: 108, present: 90, percentage: 83.3, sessionType: "Lecture", verified: true },
  { id: "a8", date: "2025-05-17", course: "CSC201 – Data Structures", school: "ABU", professor: "Prof. Akin Babatunde", enrolled: 110, present: 82, percentage: 74.5, sessionType: "Lecture", verified: false },
  { id: "a9", date: "2025-05-16", course: "CSC401 – Advanced Database Systems", school: "UNILAG", professor: "Prof. John Adeyemi", enrolled: 87, present: 80, percentage: 92.0, sessionType: "Lecture", verified: true },
  { id: "a10", date: "2025-05-16", course: "BUS401 – Strategic Management", school: "OAU", professor: "Dr. Fatima Aliyu", enrolled: 142, present: 130, percentage: 91.5, sessionType: "Seminar", verified: true },
];

export const departmentPerformance = [
  { dept: "CS", attendance: 88 },
  { dept: "EEE", attendance: 82 },
  { dept: "MEE", attendance: 77 },
  { dept: "BUS", attendance: 91 },
  { dept: "ECO", attendance: 85 },
  { dept: "MED", attendance: 96 },
];
